# Configuration:
# 
# disabled
#   false if tracking tag should be shown
# use_async
#   Set to true if you want to use asynchronous tracking
# url
#   The url of your piwik instance (e.g. localhost/piwik/
# id_site
#   The id of your website inside Piwik
#
production:
  piwik:
    id_site: 1
    url: piwik.haug-dev.de
    use_async: true
    disabled: false

development:
  piwik:
    id_site: 1
    url: piwik.haug-dev.de
    disabled: false
    use_async: false
    hostname: 127.0.0.1:3000

test:
  piwik:
    id_site: 1
    url: piwik.haug-dev.de
    disabled: true
    use_async: true
    hostname: localhost
