-- MySQL Script generated by MySQL Workbench
-- 11/13/14 11:04:29
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema WebShop_development
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WebShop_development` ;
CREATE SCHEMA IF NOT EXISTS `WebShop_development` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `WebShop_development` ;

-- -----------------------------------------------------
-- Table `WebShop_development`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`articles` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`articles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `photo_file_name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `photo_content_type` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `photo_file_size` INT(11) NULL DEFAULT NULL,
  `photo_updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`article_structures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`article_structures` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`article_structures` (
  `amount` INT(11) NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `upper_part_id` INT(11) NOT NULL DEFAULT '0',
  `lower_part_id` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`upper_part_id`, `lower_part_id`),
  INDEX `fk_article_structures_articles1_idx` (`lower_part_id` ASC),
  CONSTRAINT `fk_article_structures_articles1`
    FOREIGN KEY (`lower_part_id`)
    REFERENCES `WebShop_development`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_structures_articles2`
    FOREIGN KEY (`upper_part_id`)
    REFERENCES `WebShop_development`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`tags` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`article_to_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`article_to_tags` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`article_to_tags` (
  `article_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  INDEX `fk_article_to_tags_articles_idx` (`article_id` ASC),
  PRIMARY KEY (`article_id`, `tag_id`),
  INDEX `fk_article_to_tags_tags1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_article_to_tags_articles`
    FOREIGN KEY (`article_id`)
    REFERENCES `WebShop_development`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_to_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `WebShop_development`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`users` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `lastname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `password_digest` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `remember_digest` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `role` INT(11) NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`bills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`bills` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`bills` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bills_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_bills_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `WebShop_development`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`bill_entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`bill_entries` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`bill_entries` (
  `amount` INT(11) NULL DEFAULT NULL,
  `bill_id` INT(11) NOT NULL DEFAULT '0',
  `article_id` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`bill_id`, `article_id`),
  INDEX `fk_bill_entries_articles1_idx` (`article_id` ASC),
  CONSTRAINT `fk_bill_entries_bills1`
    FOREIGN KEY (`bill_id`)
    REFERENCES `WebShop_development`.`bills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_entries_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `WebShop_development`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`menus` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`menus` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `super_menu_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menus_menus1_idx` (`super_menu_id` ASC, `id` ASC),
  CONSTRAINT `fk_menus_menus1`
    FOREIGN KEY (`super_menu_id` , `id`)
    REFERENCES `WebShop_development`.`menus` (`super_menu_id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`menu_to_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`menu_to_tags` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`menu_to_tags` (
  `menu_id` INT(11) NOT NULL DEFAULT NULL,
  `tag_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  INDEX `fk_menu_to_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_menu_to_tags_menus1_idx` (`menu_id` ASC),
  PRIMARY KEY (`menu_id`, `tag_id`),
  CONSTRAINT `fk_menu_to_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `WebShop_development`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_to_tags_menus1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `WebShop_development`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`news` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`news` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `content` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `WebShop_development`.`shopping_cart_entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WebShop_development`.`shopping_cart_entries` ;

CREATE TABLE IF NOT EXISTS `WebShop_development`.`shopping_cart_entries` (
  `amount` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL DEFAULT '0',
  `article_id` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `article_id`),
  INDEX `fk_shopping_cart_entries_articles1_idx` (`article_id` ASC),
  CONSTRAINT `fk_shopping_cart_entries_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `WebShop_development`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_cart_entries_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `WebShop_development`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
